include:
  - https://gitlab.ddgcorp.ru/devops/ci/raw/master/build_nodejs.yml

stages:
  - build
  - save

variables:
  ARTIFACTS_DIR: dist/teorema-mobile

build:
  tags: 
    - teorema_docker
  stage: build
  image: node:11.3
  extends: .build_nodejs
  artifacts:
    expire_in: 30 days
  script:
    - npm i
    - npm run build
    
save:
  tags: 
    - teorema_shell
  stage: save
  variables:
    GIT_STRATEGY: none
  dependencies:
    - build
  script:
    - rm -rf /var/teorema/cache/${CI_PROJECT_NAME}
    - cp -r ${ARTIFACTS_DIR} /var/teorema/cache/${CI_PROJECT_NAME}