include:
  - https://gitlab.ddgcorp.ru/devops/ci/raw/master/build_nodejs.yml

stages:
  - build
  - save

build:
  tags: 
    - teorema_docker
  stage: build
  image: node:11.3
  extends: .build_nodejs
  variables:
    ARTIFACTS_DIR: dist/teorema-mobile
  script:
    - npm i
    - npm run build
    
save:
  tags: 
    - teorema_shell
  stage: save
  variables:
    GIT_STRATEGY: none
  dependencies:
    - build
  script:
    - rm -rf /var/teorema/cache/${CI_PROJECT_NAME}
    - cp -r . /var/teorema/cache/${CI_PROJECT_NAME}