stages:
  - build
  - save

variables:
  ARTIFACTS_DIR: dist/teorema-mobile

build:
  services:
    - docker:dind
  tags: 
    - teorema_docker
  stage: build
  image: node:11.3
  artifacts:
    expire_in: 30 days
    paths:
      - ${ARTIFACTS_DIR}/
  cache:
    key: $CI_PROJECT_NAME-node-cache
    paths:
      - $NODE_DIR/node_modules/
      - $NODE_DIR/*.lock
      - $NODE_DIR/package-lock.json
  script:
    - npm i
    - npm run build
    
save:
  tags: 
    - teorema_shell
  stage: save
  variables:
    GIT_STRATEGY: none
  dependencies:
    - build
  script:
    - rm -rf /var/teorema/cache/${CI_PROJECT_NAME}
    - cp -r ${ARTIFACTS_DIR} /var/teorema/cache/${CI_PROJECT_NAME}